version: '3'
services:
  dig-client:
    container_name: dig-client
    build:
      context: ./Docker_build/dig_client
      dockerfile: Dockerfile
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      bind_internal_dns:
        ipv4_address: 172.20.0.5
        ipv6_address: 2001:12a:1::5
  bind-cache:
    container_name: bind-cache
    image: ubuntu/bind9:latest
    #build:
    #  context: ./Docker_build/bind_build_22.04
    #  dockerfile: Dockerfile
    #cap_add:
    #  - NET_ADMIN
    tty: true
    volumes:
      - ./bind_config/cache/config/named.conf:/etc/bind/named.conf:rw
      - ./bind_config/cache/records/:/var/lib/bind:rw 
    networks:
      bind_internal_dns:
        ipv4_address: 172.20.0.10
        ipv6_address: 2001:12a:1::10
    #ports:
    #  - '127.0.0.1:5355:53/tcp'
    #  - '127.0.0.1:5355:53/udp'
    #  - '[::1]:5355:53/tcp'
    #  - '[::1]:5355:53/udp'
  bind-root01:
    container_name: bind-root01
    image: ubuntu/bind9:latest
    volumes:
      - ./bind_config/root/config/named.conf:/etc/bind/named.conf:rw
      - ./bind_config/root/records/:/var/lib/bind:rw 
    networks:
      bind_internal_dns:
        ipv4_address: 172.20.0.30
        ipv6_address: 2001:12a:1::30
  bind-root02:
    container_name: bind-root02
    image: ubuntu/bind9:latest
    volumes:
      - ./bind_config/root/config/named.conf:/etc/bind/named.conf:rw
      - ./bind_config/root/records/:/var/lib/bind:rw 
    networks:
      bind_internal_dns:
        ipv4_address: 172.20.0.31
        ipv6_address: 2001:12a:1::31
  bind-com01:
    container_name: bind-com01
    image: ubuntu/bind9:latest
    volumes:
      - ./bind_config/com/config/named.conf:/etc/bind/named.conf:rw
      - ./bind_config/com/records/:/var/lib/bind:rw 
    networks:
      bind_internal_dns:
        ipv4_address: 172.20.0.40
        ipv6_address: 2001:12a:1::40
  bind-com02:
    container_name: bind-com02
    image: ubuntu/bind9:latest
    volumes:
      - ./bind_config/com/config/named.conf:/etc/bind/named.conf:rw
      - ./bind_config/com/records/:/var/lib/bind:rw 
    networks:
      bind_internal_dns:
        ipv4_address: 172.20.0.41
        ipv6_address: 2001:12a:1::41
  bind-example01:
    container_name: bind-example01
    image: ubuntu/bind9:latest
    volumes:
      - ./bind_config/example.com/config/named.conf:/etc/bind/named.conf:rw
      - ./bind_config/example.com/records/:/var/lib/bind:rw 
    networks:
      bind_internal_dns:
        ipv4_address: 172.20.0.50
        ipv6_address: 2001:12a:1::50
  bind-example02:
    container_name: bind-example02
    image: ubuntu/bind9:latest
    volumes:
      - ./bind_config/example.com/config/named.conf:/etc/bind/named.conf:rw
      - ./bind_config/example.com/records/:/var/lib/bind:rw 
    networks:
      bind_internal_dns:
        ipv4_address: 172.20.0.51
        ipv6_address: 2001:12a:1::51
  bind-example03:
    container_name: bind-example03
    image: ubuntu/bind9:latest
    volumes:
      - ./bind_config/example.com/config/named.conf:/etc/bind/named.conf:rw
      - ./bind_config/example.com/records/:/var/lib/bind:rw 
    networks:
      bind_internal_dns:
        ipv4_address: 172.20.0.52
        ipv6_address: 2001:12a:1::52
  bind-example04:
    container_name: bind-example04
    image: ubuntu/bind9:latest
    volumes:
      - ./bind_config/example.com/config/named.conf:/etc/bind/named.conf:rw
      - ./bind_config/example.com/records/:/var/lib/bind:rw 
    networks:
      bind_internal_dns:
        ipv4_address: 172.20.0.53
        ipv6_address: 2001:12a:1::53
networks:
  bind_internal_dns:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
        - subnet: 2001:12a:1::/64
          gateway: 2001:12a:1::1
