services:
  bind-root01:
    container_name: bind-root01
    shm_size: 1g
    image: docker.io/ubuntu/bind9:latest
    volumes:
      - ./bind_config_ex02/root/config/named.conf:/etc/bind/named.conf
      - ./bind_config_ex02/root/records/:/var/lib/bind 
    ports:
    - "192.168.111.20:53:53/udp"
    - "192.168.111.20:53:53/tcp"
  bind-root02:
    container_name: bind-root02
    shm_size: 1g
    image: docker.io/ubuntu/bind9:latest
    volumes:
      - ./bind_config_ex02/root/config/named.conf:/etc/bind/named.conf
      - ./bind_config_ex02/root/records/:/var/lib/bind 
    ports:
    - "192.168.111.21:53:53/udp"
    - "192.168.111.21:53:53/tcp"
  bind-com01:
    container_name: bind-com01
    shm_size: 1g
    image: docker.io/ubuntu/bind9:latest
    volumes:
      - ./bind_config_ex02/com/config/named.conf:/etc/bind/named.conf
      - ./bind_config_ex02/com/records/:/var/lib/bind 
    ports:
    - "192.168.111.22:53:53/udp"
    - "192.168.111.22:53:53/tcp"
  bind-com02:
    container_name: bind-com02
    shm_size: 1g
    image: docker.io/ubuntu/bind9:latest
    volumes:
      - ./bind_config_ex02/com/config/named.conf:/etc/bind/named.conf
      - ./bind_config_ex02/com/records/:/var/lib/bind 
    ports:
    - "192.168.111.23:53:53/udp"
    - "192.168.111.23:53:53/tcp"
  bind-example01:
    container_name: bind-example01
    shm_size: 1g
    image: docker.io/ubuntu/bind9:latest
    volumes:
      - ./bind_config_ex02/example.com/config/named.conf:/etc/bind/named.conf
      - ./bind_config_ex02/example.com/records/:/var/lib/bind 
    ports:
    - "192.168.111.24:53:53/udp"
    - "192.168.111.24:53:53/tcp"
  bind-example02:
    container_name: bind-example02
    shm_size: 1g
    image: docker.io/ubuntu/bind9:latest
    volumes:
      - ./bind_config_ex02/example.com/config/named.conf:/etc/bind/named.conf
      - ./bind_config_ex02/example.com/records/:/var/lib/bind 
    ports:
    - "192.168.111.25:53:53/udp"
    - "192.168.111.25:53:53/tcp"
  bind-example03:
    container_name: bind-example03
    shm_size: 1g
    image: docker.io/ubuntu/bind9:latest
    volumes:
      - ./bind_config_ex02/example.com/config/named.conf:/etc/bind/named.conf
      - ./bind_config_ex02/example.com/records/:/var/lib/bind 
    ports:
    - "192.168.111.26:53:53/udp"
    - "192.168.111.26:53:53/tcp"
  bind-example04:
    container_name: bind-example04
    shm_size: 1g
    image: docker.io/ubuntu/bind9:latest
    volumes:
      - ./bind_config_ex02/example.com/config/named.conf:/etc/bind/named.conf
      - ./bind_config_ex02/example.com/records/:/var/lib/bind 
    ports:
    - "192.168.111.27:53:53/udp"
    - "192.168.111.27:53:53/tcp"
